# .github/release.yml

changelog:
  exclude:
    labels:
      - meta
      - test
  categories:
    - title: New Features
      labels:
        - feat
    - title: Bug Fixes
      labels:
        - bug
    - title: Dependency Updates
      labels:
        - dependencies
    - title: Documentation Changes
      labels:
        - doc
