openapi: 3.0.0
info:
  title: Example OpenAPI Spec.
  description: An example OpenAPI-spec to generate example Java records.
  version: 0.0.1

servers:
  - url: http://localhost/
    description: Irrelevant

paths:
  /ignore:
    get:
      summary: Ignore
      description: Irrelevant
      responses:
        '200':
          description: OK

components:
  schemas:
    ExampleRecord:
      type: object
      properties:
        field:
          type: boolean
    DeprecatedExampleRecord:
      type: object
      deprecated: true
      properties:
        field:
          type: boolean
    ExampleRecordWithStringFields:
      type: object
      properties:
        field1:
          type: string
        field2:
          type: string
        field3:
          type: string
    ExampleRecordWithIntegerFields:
      type: object
      properties:
        field1:
          type: integer
        field2:
          type: integer
        field3:
          type: integer
    ExampleEnum:
      description: Example Enum
      type: string
      enum:
        - FIRST_ENUM
        - SECOND_ENUM
    ExampleDeprecatedObject:
      description: Example Deprecated object
      deprecated: true
      type: object
      required:
        - id
        - text
      properties:
        id:
          description: Identifier
          type: integer
        text:
          type: string
    ExampleObject:
      description: Example Object
      type: object
      required:
        - id
        - text
      properties:
        id:
          description: Identifier
          type: integer
        text:
          type: string
    ExampleObjectWithArray:
      description: Example Object with Array
      type: object
      required:
        - collection
      properties:
        collection:
          description: Collection
          type: array
          items:
            type: integer
    ExampleCompositeObject:
      description: Example Composite Object
      type: object
      required:
        - composite
      properties:
        composite:
          $ref: '#/components/schemas/ExampleObject'