openapi: 3.0.0
info:
  title: Example OpenAPI Spec.
  description: An example OpenAPI-spec to generate example Java records.
  version: 0.0.1

servers:
  - url: http://localhost/
    description: Irrelevant

paths:
  /ignore:
    get:
      summary: Ignore
      description: Irrelevant
      responses:
        '200':
          description: OK

components:
  schemas:
    ExampleRecord:
      type: object
      properties:
        field:
          type: boolean
    DeprecatedExampleRecord:
      type: object
      deprecated: true
      properties:
        field:
          type: boolean
    ExampleRecordWithStringFields:
      type: object
      properties:
        field1:
          type: string
        field2:
          type: string
        field3:
          type: string
    ExampleRecordWithIntegerFields:
      type: object
      properties:
        field1:
          type: integer
        field2:
          type: integer
        field3:
          type: integer
    ExampleRecordWithBooleanFields:
      type: object
      properties:
        field1:
          type: boolean
        field2:
          type: boolean
        field3:
          type: boolean
    ExampleRecordWithArrayFields:
      type: object
      properties:
        field1:
          type: array
          items:
            type: boolean
        field2:
          type: array
          items:
            type: boolean
        field3:
          type: array
          items:
            type: boolean
    ###### NOT SUPPORTED YET ######
    #ExampleRecordWithNumberFields:
    #  type: object
    #  properties:
    #    field1:
    #      type: number
    #    field2:
    #      type: number
    #    field3:
    #      type: number
    ###############################
    ExampleRecordWithExampleRecordFields:
      type: object
      properties:
        field1:
          $ref: '#/components/schemas/ExampleRecord'
        field2:
          $ref: '#/components/schemas/ExampleRecord'
        field3:
          $ref: '#/components/schemas/ExampleRecord'
    ExampleRecordWithExampleEnumFields:
      type: object
      properties:
        field1:
          $ref: '#/components/schemas/ExampleEnum'
        field2:
          $ref: '#/components/schemas/ExampleEnum'
        field3:
          $ref: '#/components/schemas/ExampleEnum'
    ExampleEnum:
      type: string
      enum:
        - ENUM1
        - ENUM2
        - ENUM3
    ExampleDeprecatedObject:
      description: Example Deprecated object
      deprecated: true
      type: object
      required:
        - id
        - text
      properties:
        id:
          description: Identifier
          type: integer
        text:
          type: string
    ExampleObject:
      description: Example Object
      type: object
      required:
        - id
        - text
      properties:
        id:
          description: Identifier
          type: integer
        text:
          type: string
    ExampleObjectWithArray:
      description: Example Object with Array
      type: object
      required:
        - collection
      properties:
        collection:
          description: Collection
          type: array
          items:
            type: integer
    ExampleCompositeObject:
      description: Example Composite Object
      type: object
      required:
        - composite
      properties:
        composite:
          $ref: '#/components/schemas/ExampleObject'