openapi: 3.0.0
info:
  title: Example OpenAPI Spec.
  description: An example OpenAPI-spec to generate example Java records.
  version: 0.0.1

servers:
  - url: http://localhost/
    description: Irrelevant

paths:
  /ignore:
    get:
      summary: Ignore
      description: Irrelevant
      responses:
        '200':
          description: OK

components:
  schemas:
    ExampleRecordWithRequiredFieldsOfEachType:
      type: object
      description: Example of a Record with fields of each type
      required:
        - field1
        - field2
        - field3
        - field4
        - field5
        - field6
        - field7
        - field8
      properties:
        field1:
          type: boolean
          description: a Boolean field
        field2:
          type: string
          description: a String field
        field3:
          type: integer
          description: an Integer field
        field4:
          type: number
          description: a Number field
        field5:
          type: array
          description: an Array of Boolean field
          items:
            type: boolean
        field6:
          type: array
          description: a Set field
          uniqueItems: true
          items:
            type: boolean
        field7:
          description: an ExampleRecord field
          $ref: '#/components/schemas/ExampleRecord'
        field8:
          description: an ExampleEnum field
          $ref: '#/components/schemas/ExampleEnum'
    ExampleRecordWithNullableFieldsOfEachType:
      type: object
      description: Example of a Record with fields of each type
      required:
        - field1
        - field2
        - field3
        - field4
        - field5
        - field6
        - field7
        - field8
      properties:
        field1:
          type: boolean
          description: a Boolean field
          nullable: true
        field2:
          type: string
          description: a String field
          nullable: true
        field3:
          type: integer
          description: an Integer field
          nullable: true
        field4:
          type: number
          description: a Number field
          nullable: true
        field5:
          type: array
          description: an Array of Boolean field
          nullable: true
          items:
            type: boolean
        field6:
          type: array
          description: a Set field
          uniqueItems: true
          nullable: true
          items:
            type: boolean
    ExampleRecord:
      type: object
      description: Example of a Record
      properties:
        field1:
          type: boolean
          description: a boolean field
    DeprecatedExampleRecord:
      type: object
      deprecated: true
      description: Example of a deprecated Record
      properties:
        field1:
          type: boolean
          description: a boolean field
    ExampleRecordWithDefaultFields:
      type: object
      description: Example of a Record with default fields
      properties:
        field1:
          type: string
          description: a String field with a default value
          default: someDefaultValue
    ExampleEnum:
      type: string
      description: Example of an Enum
      enum:
        - ENUM1
        - ENUM2
        - ENUM3
    DeprecatedExampleEnum:
      type: string
      deprecated: true
      description: Example of a deprecated Enum
      enum:
        - ENUM1
        - ENUM2
        - ENUM3
