openapi: 3.0.0
info:
  title: Example OpenAPI Spec.
  description: An example OpenAPI-spec to generate example Java records.
  version: 0.0.1

servers:
  - url: http://localhost/
    description: Irrelevant

paths:
  /ignore:
    get:
      summary: Ignore
      description: Irrelevant
      responses:
        '200':
          description: OK

components:
  schemas:
    ExampleRecord:
      type: object
      description: Example of a Record
      properties:
        field1:
          type: boolean
          description: a boolean field
    DeprecatedExampleRecord:
      type: object
      deprecated: true
      description: Example of a deprecated Record
      properties:
        field1:
          type: boolean
          description: a boolean field
    ExampleRecordWithStringFields:
      type: object
      description: Example of a Record with String fields
      properties:
        field1:
          type: string
          description: a String field
        field2:
          type: string
          description: another String field
        field3:
          type: string
          description: yet another String field
    ExampleRecordWithIntegerFields:
      type: object
      description: Example of a Record with Integer fields
      properties:
        field1:
          type: integer
          description: a Integer field
        field2:
          type: integer
          description: another Integer field
        field3:
          type: integer
          description: yet another Integer field
    ExampleRecordWithBooleanFields:
      type: object
      description: Example of a Record with Boolean fields
      properties:
        field1:
          type: boolean
          description: a Boolean field
        field2:
          type: boolean
          description: another Boolean field
        field3:
          type: boolean
          description: yet another Boolean field
    ExampleRecordWithArrayFields:
      type: object
      description: Example of a Record with Array fields
      properties:
        field1:
          type: array
          description: an Array field
          items:
            type: boolean
        field2:
          type: array
          description: another Array field
          items:
            type: boolean
        field3:
          type: array
          description: yet another Array field
          items:
            type: boolean
    ExampleRecordWithNumberFields:
      type: object
      description: Example of a Record with Number fields
      properties:
        field1:
          type: number
          description: a Number field
        field2:
          type: number
          description: another Number field
        field3:
          type: number
          description: yet another Number field
    ExampleRecordWithExampleRecordFields:
      type: object
      description: Example of a Record with Record fields
      properties:
        field1:
          $ref: '#/components/schemas/ExampleRecord'
        field2:
          $ref: '#/components/schemas/ExampleRecord'
        field3:
          $ref: '#/components/schemas/ExampleRecord'
    ExampleRecordWithExampleEnumFields:
      type: object
      description: Example of a Record with Enum fields
      properties:
        field1:
          $ref: '#/components/schemas/ExampleEnum'
        field2:
          $ref: '#/components/schemas/ExampleEnum'
        field3:
          $ref: '#/components/schemas/ExampleEnum'
    ExampleRecordWithDefaultFields:
      type: object
      description: Example of a Record with default fields
      properties:
        field1:
          type: string
          description: a nullable String field
          nullable: true
        field2:
          type: string
          description: a String field with a default value
          default: someDefaultValue
    ExampleEnum:
      type: string
      description: Example of an Enum
      enum:
        - ENUM1
        - ENUM2
        - ENUM3
    DeprecatedExampleEnum:
      type: string
      deprecated: true
      description: Example of a deprecated Enum
      enum:
        - ENUM1
        - ENUM2
        - ENUM3
