title: openapi-to-java-records-mustache-templates
description: >-
  Generate Java Records from OpenAPI Specifications

repository: Chrimle/openapi-to-java-records-mustache-templates

markdown: GFM

plugins:
  - jekyll-gfm-admonitions

include:
  - README.md
