title: openapi-to-java-records-mustache-templates
description: >-
  Generate Java Records from OpenAPI Specifications

github_username: Chrimle
url: "https://github.com/Chrimle"
baseurl: "/openapi-to-java-records-mustache-templates"

repository: Chrimle/openapi-to-java-records-mustache-templates

markdown: GFM

plugins:
  - jekyll-gfm-admonitions

include:
  - README.md