name: Pull Request Auditor

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - edited
      - synchronize
      - ready_for_review

jobs:
  Label-Auditor:
    name: Label Auditor
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Label Auditor
        uses: Chrimle/Label-Auditor@cd3700cdb68e92706a422ba67ec98a22660bd86c # v0.2.0
