name: Pull Request Auditor

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - edited
      - synchronize
      - ready_for_review

permissions:
  contents: read

jobs:
  Label-Auditor:
    name: Label Auditor
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Label Auditor
        uses: Chrimle/Label-Auditor@v0.1.0
