name: Github PR Audit

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - edited
      - synchronize

jobs:
  Pull-Request-Label-Auditor:
    name: Label Auditor
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script-path: .github/workflows/scripts/label-auditor.js
